### PR TITLE
Signup Forms

### PR DESCRIPTION
**Pull request by Swastik1710**
ISSUE #94 

Added a page for the user to choose to signup as a Student or as a Teacher.
Added 2 separate sign up pages for student and teacher.

Here are the screenshots :

Option Page 

Student SignUp page

Teacher SignUp page

Student SignUp page in dark mode

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
@Swastik1710 all your submissions are decent but very basic in terms of design.
Here are some references and  we are expecting something similar to it.
https://dribbble.com/shots/15392711-Dashboard-Login-Sign-Up
https://dribbble.com/shots/15541492-Autenti-Web-App-Sign-In
https://dribbble.com/shots/6606840-Sign-Up
https://dribbble.com/shots/11879454-Sign-Up-Form

**Comment by deeqakkk** [comment]
Swastik any updates?

**Comment by deeqakkk** [comment]
any updates?

**Comment by Swastik1710** [comment]
> any updates?

Give me some time I'm working on it.

**Comment by Swastik1710** [comment]
Hey @deeqakkk , I've made the changes, please have a look.

https://swastik1710.github.io/OneEducationalWebsiteForAll/

**Comment by Swastik1710** [comment]
Student Login




Teacher Login

**Comment by Swastik1710** [comment]
And this is the Options Page 

Screenshot 2021-07-14 110000

**Comment by Akshima-Ghai** [comment]
@deeqakkk pls preview the design

**Review by deeqakkk — COMMENTED** [review]
Yes, they look decent now.

**Review by deeqakkk — APPROVED** [review]
You can make a PR.

**Comment by Swastik1710** [comment]
This is a PR only.
I've pushed all the changes. 
Please merge it.

**Pull request merged**
