### PR TITLE
Nav Bar fixed

### PR DESCRIPTION
**Pull request by AmanBisht01**
dark

issue #127

### CODE REVIEW

**Comment by AmanBisht01** [comment]
where should I place the dark mode toggle button?

**Review by deeqakkk — CHANGES_REQUESTED** [review]
It's good on the extreme right side of the navbar just maintain the color theme with the website.

**Comment by Akshima-Ghai** [comment]
This branch has conflicts that must be resolved
Conflicting files
src/components/Header/Header.js

**Comment by AmanBisht01** [comment]
conflicts resolved

**Pull request merged**
