### PR TITLE
Add Dark mode in Feature page

### PR DESCRIPTION
**Pull request by HarshitPandey251**
Solve issue: #103 

It was looking like this 
Screenshot 2021-07-10 133124
Screenshot 2021-07-10 133407
Screenshot 2021-07-10 133433

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Chnage color of navbar items on hover:
image

**Comment by HarshitPandey251** [comment]
@deeqakkk I have change navbar item color to orange while hover in dark mode

**Comment by Akshima-Ghai** [comment]
This branch has conflicts that must be resolved

Conflicting files
src/pages/Feature/Feature_student.js
src/pages/Feature/Feature_teacher.js
yarn.lock

**Comment by HarshitPandey251** [comment]
I resolve it @Akshima-Ghai

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Harshit i know you are working on feature page, but it would be nice if you can make this part a more visible in dark mode
image

one more thing that need to changed is hover effect of "sign up" button.

**Comment by HarshitPandey251** [comment]
I have given an color to a chart which I thing is looking good

**Comment by HarshitPandey251** [comment]
@Akshima-Ghai Pls Check my PR and It is nice if you give me feedback

**Pull request merged**
