### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by Swastik1710**
Added the Footer Section as mentioned in issue #52 
This would close issue #52 
Left an empty space for the Website logo and added all the required footer details.
Here's an image of the same.
Screenshot 2021-07-02 230820
Please do let me know if any changes are required.

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
@Swastik1710 That's awesome. But could you please update the colors with the theme of the website?

**Comment by Swastik1710** [comment]
Yeah sure.
Do you mind giving some suggestions regarding the same.

**Comment by Swastik1710** [comment]
Screenshot 2021-07-03 160302

The theme is based only on Orange and White so I'm unable to get much idea.
Please let me know some suggestions regarding it.

**Comment by NikhilSharma03** [comment]
@Swastik1710 Try exploring on dribbble and google. I'm sure you will get the best idea. Looking forward to see the changes you make. Let me know if there's anything i can help with.

**Comment by NikhilSharma03** [comment]
And also could you update the classes names. Please follow CSS BEM naming.
Example:-
- footer
 and the nested element should be
- footer__main
- footer__box--content

It will be more scalable this way and it won't clash with other classes.

**Comment by Akshima-Ghai** [comment]
This branch has conflicts that must be resolved
Conflicting files
src/App.js
@Swastik1710

**Comment by Swastik1710** [comment]
Screenshot 2021-07-04 195030

Hey @NikhilSharma03 , is this one fine ?

**Comment by Akshima-Ghai** [comment]
Great work @Swastik1710

**Comment by NikhilSharma03** [comment]
@Swastik1710 That's awesome.

**Comment by Swastik1710** [comment]
Hey @NikhilSharma03 @Akshima-Ghai, I haven't pushed the recent changes, I've just made the changes and presented the screenshot to you as I was expecting that you guys would suggest some changes. So shall I create a new PR for this?

**Comment by Akshima-Ghai** [comment]
Yes @Swastik1710 , that would be great

**Comment by Swastik1710** [comment]
Ohkay.
I'll do that.
Thanks.

**Pull request merged**
