### PR TITLE
doubt section added 

### PR DESCRIPTION
**Pull request by AmanBisht01**
Added FAQ section 

Design Website #38

Screenshot (103)
Screenshot (102)

### CODE REVIEW

**Comment by Akshima-Ghai** [comment]
This branch has conflicts that must be resolved
try resolving the conflicts, and also pull the changes made to the nav-bar and other detailing.
Great design, just resolve the conflicts and we will merge the issue. GOOD LUCK @AmanBisht01

**Comment by AmanBisht01** [comment]
Resolved conflicts..

**Comment by Akshima-Ghai** [comment]
@AmanBisht01 great, now select another issue and start working on it. GOOD LUCK

**Comment by AmanBisht01** [comment]
👍

**Pull request merged**
