### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by AmanBisht01**
Navbar change, theme color applied 
Screenshot (109)

Color theme maintained 
Screenshot (110)

issue #82

### CODE REVIEW

**Comment by deeqakkk** [comment]
@AmanBisht01 It's almost perfect👏 , just do a minor change in buttons to make it look like ss provided.
image

**Comment by AmanBisht01** [comment]
working on it.

**Comment by AmanBisht01** [comment]
Screenshot (114)

**Review by AmanBisht01 — COMMENTED** [review]
@deeqakkk Review Requested

**Comment by deeqakkk** [comment]
@AmanBisht01 That's perfect 👏

**Pull request merged**
