### PR TITLE
created page for blogtopics

### LINKED ISSUE #209: BLOGS Page
Create a page for blogs sections

### PR DESCRIPTION
**Pull request by ShwetKhatri2001**
### Fixes #209
- added page having some topics for blogs where each topic-card direct to its topic related blogs page onclick to it.
- its responsive too.
- @deeqakkk Review It.

### CODE REVIEW

**Review by epicdeepak — CHANGES_REQUESTED** [review]
image
Remove this blue line .
and also atleast add two pages so that we can check functionality of the buttons at bottom.

**Comment by ShwetKhatri2001** [comment]
Can I do it in next PR ? Its almost ready.

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned

**Comment by deeqakkk** [comment]
> Can I do it in next PR ? Its almost ready.

sure

**Comment by deeqakkk** [comment]
> Can I do it in next PR ? Its almost ready.

please resolve conflict.

**Comment by ShwetKhatri2001** [comment]
@deepak I have done some auth changes and blogs pages are working fine as expected

**Pull request merged**
