### PR TITLE
Changed scrolltop to left on get started page

### LINKED ISSUE #204: "Back to top" button in get started page
~Button is not visible on this page coz of the chatbox 
~Do minor tweaks to make it visible.

### PR DESCRIPTION
**Pull request by ShwetKhatri2001**
### Fixes #204 

- scrolltop button will be on left on get started page and on right on other pages.

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Plz make it noticeable when it just got enabled.
you can add some animation like pop out or twinkle.

**Comment by ShwetKhatri2001** [comment]
We already have issue #203 for that

**Comment by deeqakkk** [comment]
> We already have issue #203 for that

Yes, that I obviously know.
But if you are working on an issue then you should try to make it perfect from yoursside.

**Comment by deeqakkk** [comment]
> We already have issue #203 for that

Yes, that I obviously know.
But if you are working on an issue then you should try to make it perfect from your side.

**Review by deeqakkk — APPROVED** [review]

**Pull request merged**
